const styles = {
    root: {
        backgroundColor: '#EFEFEF',
        padding: 0,
        margin: 0,
    },
    header: {
        display: 'flex',
        flex: 0,
        width: '100%',
        height: '80px',
        backgroundColor: '#FFFFFF',
        boxShadow: '0px 3px 3px #00000029',
        alignItems: 'center',
        padding: '0px',
        justifyContent: 'space-between',
    },
    toolbar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
    },
    logo: {
        height: '50px',
        marginRight: '20px',
    },
    locationSection: {
        display: 'flex',
        alignItems: 'center',
        color: '#962067'
    },
    dropdown: {
        marginLeft: '10px',
        marginRight: '10px',
    },
    instructions: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        padding: '20px',
    },
    ins1: {
        fontFamily: 'Poppins',
        fontSize: '32px',
        lineHeight: '40px',
        letterSpacing: '0px',
        color: '#962067',
        opacity: 1,
        '@media (max-width: 600px)': {
            fontSize: '24px',
            lineHeight: '30px',
        },
    },
    ins2: {
        fontFamily: 'Poppins',
        fontSize: '22px',
        lineHeight: '30px',
        letterSpacing: '0px',
        color: '#58595B',
        opacity: 1,
        '@media (max-width: 600px)': {
            fontSize: '18px',
            lineHeight: '24px',
        },
    },
    ins3: {
        fontFamily: 'Poppins',
        fontSize: '18px',
        lineHeight: '24px',
        letterSpacing: '0px',
        color: '#939598',
        opacity: 1,
        '@media (max-width: 600px)': {
            fontSize: '16px',
            lineHeight: '20px',
        },
    },
    searchBar: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        margin: '20px 0',
        width: '100%',
    },
    searchInput: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderColor: '#962067',
        margin: '0 10px',
    },
    locationDropdown: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderColor: '#962067',
        margin: '0 10px',
    },
    searchButton: {
        flexShrink: 0,
        height: '55px',
        background: '#962067',
        color: '#FFFFFF',
        boxShadow: '0px 3px 6px #00000029',
        borderRadius: '26px',
        margin: '0 10px',
    },
    secondSplit: {
        display: 'flex',
        width: '100%',
        backgroundColor: '#FFF7FB',
        justifyContent: 'space-between',
        padding: '20px',
        marginTop: '5px',
        flexWrap: 'wrap',
    },
    imageSection: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        margin: '20px 0',
    },
    menuIcons: {
        display: 'flex',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: '10px',
    },
    image: {
        width: '100%',
        height: 'auto',
    },
    thirdSplit: {
        display: 'flex',
        width: '100%',
        backgroundColor: '#FFFFFF',
        borderRadius: '10px',
        padding: '20px',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: '8px',
    },
    zigZag: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
    },
    zigZagRow: {
        display: 'flex',
        alignItems: 'center',
        marginBottom: '20px',
    },
    zigZagImage: {
        marginRight: '10px',
    },
    scanners: {
        display: 'flex',
        justifyContent: 'space-around',
        marginBottom: '20px',
    },
    scanner: {
        width: '150px',
        height: '150px',
    },
    rightContent: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        padding: '20px',
    },
    cards: {
        display: 'flex',
        justifyContent: 'space-around',
        marginBottom: '20px',
        flexWrap: 'wrap',
    },
    card: {
        width: '45%',
        marginBottom: '20px',
    },
    videos: {
        display: 'flex',
        justifyContent: 'space-around',
        width: '100%',
        flexWrap: 'wrap',
    },
    video: {
        width: '45%',
        height: '300px',
        marginBottom: '20px',
    },
    fourthSplit: {
        display: 'flex',
        width: '100%',
        backgroundColor: '#FFFFFF',
        borderRadius: '10px',
        padding: '20px',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: '8px',
    },
    cardGrid: {
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        width: '100%',
    },
    gridCard: {
        width: '22%',
        marginBottom: '20px',
        '@media (max-width: 960px)': {
            width: '45%',
        },
        '@media (max-width: 600px)': {
            width: '100%',
        },
    },
    seeMoreButton: {
        display: 'block',
        margin: '0 auto',
    },
    footer: {
        display: 'flex',
        width: '100%',
        height: '80px',
        backgroundColor: '#962067',
        borderRadius: '10px 10px 0px 0px',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: '8px',
    },
};

export default styles;
