import Images from './constants/Images.js';

const styles = {
    root: {
        backgroundColor: '#EFEFEF',
        padding: 0,
        margin: 0,
    },
    header: {
        display: 'flex',
        flex: 0,
        width: '100%',
        height: '80px',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        padding: '0px',
        justifyContent: 'space-between',
        '@media (max-width: 600px)': {
            height: '60px',
        },
    },
    toolbar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
    },
    logo: {
        height: '70px',
        marginLeft: '20px',
        '@media (max-width: 600px)': {
            height: '50px',
            marginLeft: '10px',
        },
    },
    locationSection: {
        display: 'flex',
        color: '#962067',
        textAlign: "left",
        alignItems: 'center',
        font: "normal normal normal 18px/27px Poppins",
        letterSpacing: "0px",
        width: '24px',
        height: '35px',
        '@media (max-width: 600px)': {
            fontSize: '14px',
            width: '20px',
            height: '30px',
        },
    },
    instructions: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        padding: '20px',
    },
    ins1: {
        fontFamily: 'Poppins',
        paddingTop: '10px',
        fontSize: '50px',
        lineHeight: '40px',
        letterSpacing: '0px',
        color: '#962067',
        opacity: 1,
        '@media (max-width: 600px)': {
            fontSize: '24px',
            lineHeight: '30px',
        },
    },
    ins2: {
        fontFamily: 'Poppins',
        fontSize: '30px',
        lineHeight: '30px',
        letterSpacing: '0px',
        color: '#58595B',
        opacity: 1,
        '@media (max-width: 600px)': {
            fontSize: '18px',
            lineHeight: '24px',
        },
    },
    ins3: {
        fontFamily: 'Poppins',
        fontSize: '22px',
        lineHeight: '24px',
        letterSpacing: '0px',
        color: '#939598',
        opacity: 1,
        '@media (max-width: 600px)': {
            fontSize: '16px',
            lineHeight: '20px',
        },
    },
    searchBar: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',  
        width: '100%',
        backgroundImage: `url(${Images.family_front})`,
    },
    serachtext: {
        position: 'relative',
        bottom: '60%',
        left: '40%',
        letterSpacing: '0px',
        color: '#58595B',
        opacity: 1,
        width: '50%',
    },
    locationDropdown: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderColor: '#962067',
        margin: '0 10px',
    },
    searchButton: {
        width: '300px',
        margin: '0 20px',
        height: '50px',
        background: '#FFFFFF 0% 0% no-repeat padding-box',
        boxShadow: '0px 3px 6px #00000029',
        border: '1px solid #E9AFB7',
        fontFamily: 'Poppins',
        borderRadius: '35px',
        color: '#58595B',
        fontSize: '26px',
        fontWeight: 'regular',
        opacity: 1,
        '@media (max-width: 600px)': {
            width: '100%',
            fontSize: '18px',
            height: '40px',
        },
    },
    searchmain: {
        background: '#962067 0% 0% no-repeat padding-box',
        color: 'white',
        width: '70px',
        height: '28px',
        boxShadow: '0px 3px 6px #00000029',
        fontStyle: 'Poppins',
        fontFamily: 'Poppins',
        borderRadius: '26px',
        position: 'absolute',
        left: '30%',
        opacity: 1,
    },
    search: {
        position: 'relative',
        width: '100%',
        display: 'flex',
        alignItems: 'center',
    },
    searchContainer: {
        position: 'relative',
        width: '100%',
    },
    searchfield: {
        width: '70%',
        padding: '10px',
        borderColor: '#962067',
        position: 'relative',
        right: '50%',
        background: '#FFFFFF 0% 0% no-repeat padding-box',
        border: '1px solid #962067',
        borderRadius: '35px',
        opacity: 1,
        '@media (max-width: 600px)': {
            width: '100%',
            padding: '5px',
        },
    },
    searchIcon: {
        height: '1.5rem',
        width: '1.5rem',
        padding: '4px',
        position: 'absolute',
        alignItems: 'right',
        boxSizing: 'border-box',
        top: '50%',
        left: '2px',
        transform: 'translateY(-50%)',
    },
    secondSplit: {
        display: 'flex',
        width: '100%',
        backgroundColor: '#FFF7FB',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
    },
    buttext: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        width: '100%',
        height: '55px',
        borderRadius: '35px',
        opacity: 1,
        font: 'normal normal normal 17px Poppins',
        letterSpacing: '0px',
    },
    qrtext: {
        display: 'flex',
        alignItems: 'left',
        position: 'relative',
        right: '15%',
        width: '60%',
        height: '55px',
        borderRadius: '35px',
        opacity: 1,
        font: 'normal normal normal 17px Poppins',
        letterSpacing: '0px',
    },
    imageSection: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        margin: '0 0',
    },
    qrimage: {
        width: '5%',
        borderWidth: '10px',
        marginLeft: '10%',
        display: 'block',
        alignSelf: 'flex-start',
    },
    thirdSplit: {
        display: 'flex',
        width: '95%',
        backgroundColor: '#FFFFFF',
        borderRadius: '10px',
        alignItems: 'center',
        marginTop: '2%',
        marginLeft: '3%',
        marginRight: '4%',
        '@media (max-width: 600px)': {
            flexDirection: 'column',
            width: '100%',
            marginLeft: '0',
            marginRight: '0',
        },
    },
    tt1: {
        fontFamily: 'Poppins',
        paddingTop: '10px',
        fontSize: '40px',
        lineHeight: '40px',
        display: 'flex',
        justifyContent: 'center',
        letterSpacing: '0px',
        color: '#962067',
        opacity: 1,
        '@media (max-width: 600px)': {
            fontSize: '24px',
            lineHeight: '30px',
        },
    },
    tt2: {
        fontFamily: 'Poppins',
        fontSize: '30px',
        lineHeight: '30px',
        display: 'flex',
        justifyContent: 'center',
        letterSpacing: '0px',
        color: '#58595B',
        opacity: 1,
        '@media (max-width: 600px)': {
            fontSize: '18px',
            lineHeight: '24px',
        },
    },
    tt3: {
        fontFamily: 'Poppins',
        display: 'flex',
        justifyContent: 'center',
        fontSize: '22px',
        lineHeight: '24px',
        letterSpacing: '0px',
        color: '#939598',
        opacity: 1,
        '@media (max-width: 600px)': {
            fontSize: '16px',
            lineHeight: '20px',
        },
    },
    eventCalander: {
        width: '237px',
        height: '237px',
        position: 'relative',
        left: '43%',
        opacity: 1,
        '@media (max-width: 600px)': {
            width: '100%',
            height: 'auto',
            left: '0',
        },
    },
    pastSection: {
        display: 'flex',
        flex: 0,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    pastmain: {
        display: 'flex',
        flex: 0,
        width: '100%',
        height: '27px',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        padding: '0px',
        justifyContent: 'space-between',
    },
    imageRounded: {
        width: '150px',
        height: '150px',
        borderRadius: '50%',
        marginBottom: '20px',
        '@media (max-width: 600px)': {
            width: '100px',
            height: '100px',
        },
    },
    gridContainer: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
        gap: '20px',
        justifyContent: 'center',
        alignItems: 'center',
        '@media (max-width: 600px)': {
            gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
        },
    },
    feature: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        textAlign: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: '10px',
        padding: '20px',
        boxShadow: '0px 3px 6px #00000029',
    },
    title: {
        fontSize: '20px',
        fontWeight: 'bold',
        marginBottom: '10px',
        '@media (max-width: 600px)': {
            fontSize: '18px',
        },
    },
    description: {
        fontSize: '16px',
        color: '#58595B',
        '@media (max-width: 600px)': {
            fontSize: '14px',
        },
    },
};

export default styles;
